[project]
name = "multi-armed-bandit-simulation"
version = "0.1.0"
description = "Multi armed bandit simulation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["matplotlib>=3.10.5", "pandas>=2.3.1", "scipy>=1.16.1"]
